### ISSUE TITLE
Debt auction lot quantity does not equal corresponding debt

### ISSUE THREAD

**Issue by denalimarsh** [Kava-Labs/kava#339]
Quantity of `ukava` auctioned in a debt auction has 2 additional digit places than it should. Debt auction query res result:

```
base_auction:
  id: 8
  initiator: liquidator
  lot:
    denom: ukava
    amount: "1050000000"
  bidder: kava1eu2ta269haf6j6z3lsj79a8rq3hsmnhu689g7z
  bid:
    denom: usdx
    amount: "10500000"
  has_received_bids: false
  end_time: 9000-01-01T00:00:00Z
  max_end_time: 9000-01-01T00:00:00Z
corresponding_debt:
  denom: debt
  amount: "10500000"
``` 

@rhuairahrighairidh can you duplicate this query res? I have some ideas about what's wrong but want to confirm it's not my genesis config.
