### ISSUE TITLE
Update CDP's accumulated fees and fee's updated time on query CDP

### ISSUE THREAD

**Issue by denalimarsh** [Kava-Labs/kava#366]
Accumulated fees are only updated on CDP actions. For CDP queries, the accumulated fees are calculated in memory and used to calculate the collateralization ratio, but the state of the CDP is not updated. Therefore, a CDP query result will almost always have a collateralization ratio that doesn't match the accumulated fees:
```
- cdp:
    id: 1
    owner: kava1xy7hrjy9r0algz9w3gzm8u6mrpq97kwta747gj
    collateral:
    - denom: xrp
      amount: "80000000"
    principal:
    - denom: usdx
      amount: "10000000"
    accumulated_fees: []
    fees_updated: 2020-02-08T17:07:16.233114Z
  collateral_value:
    denom: usdx
    amount: "20000000"
  collateralization_ratio: "1.999997200003919995"
```

We could insert the accumulated fees into the AugmentedCDP query result object _or_ update CDP state before returning the result. Does a CLI query updating state go against best practices?
